{
 "title": "AOCryptoBot",
 "time": { "from": "2022-09-16T22:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Strategies",
    "label": "Strategies",
    "query": "Lun1MarCustomStrategy,Lun5JulCustomStrategy,MACDCustomStrategy,MixedStrategy1,StableStrategy,StochRSICustomStrategy,MACDInStochRSIOutCustomStrategy,StochRSIInMACDOutCustomStrategy"
   },
   {
    "name": "var_symbol",
    "label": "Symbol",
    "query": "SELECT symbol FROM positions GROUP BY symbol"
   }
  ]
 },
 "panels": [
  {
   "title": "Benefit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(gain) as BENEFIT FROM positions WHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000"
    }
   ]
  },
  {
   "title": "Profit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (avg(profit) * count(profit))/ 3 as \"Profit\"\nFROM positions WHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000"
    }
   ]
  },
  {
   "title": "Average Profit p.p.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(profit) as \"Avg Profit\"\nFROM positions WHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000"
    }
   ]
  },
  {
   "title": "Average Strategy Profits p.p.",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  strategy,\n  avg(profit) AS \"Avg Profit\"\nFROM positions\nWHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nGROUP BY strategy\nORDER by avg(profit) desc"
    }
   ]
  },
  {
   "title": "Sum Strategy Profits",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  strategy,\n  avg(profit) * count(profit) AS \"Profit\"\nFROM positions\nWHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nGROUP BY strategy\nORDER by avg(profit) * count(profit) desc"
    }
   ]
  },
  {
   "title": "Open Positions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    positions.symbol as \"Symbol\",\n    positions.entry_time * 1000  AS \"Entry Time\",\n    positions.strategy as \"Strategy\",\n    (candles.close_price * 100 / orders.price) - 100.14 as \"Current Profit (Live)\"\nFROM positions INNER JOIN candles ON positions.symbol = candles.symbol JOIN orders ON positions.id = orders.position_id\nWHERE\n   $__timeFilter(positions.updated_at) AND positions.strategy IN($Strategies) AND positions.symbol IN($var_symbol) \n   AND profit = -1000 AND orders.side = \"BUY\" AND candles.id = (SELECT c2.id FROM candles AS c2 WHERE c2.symbol = positions.symbol ORDER BY c2.period DESC LIMIT 1)\nORDER BY candles.period DESC"
    }
   ]
  },
  {
   "title": "Closed Positions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  symbol as \"Symbol\",\n  exit_time*1000 as \"Exit Time\",\n  strategy as \"Strategy\",\n  exit_trigger AS \"Trigger\",\n  profit AS \"Profit\"\nFROM positions\nWHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nORDER BY exit_time DESC"
    }
   ]
  },
  {
   "title": "ETHEUR Binance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "Time", "type": "timestamp_epoch" },
      { "selector": "4", "text": "Value", "type": "number" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api1.binance.com/api/v3/klines?symbol=ETHEUR&interval=12h",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    }
   ]
  },
  {
   "title": "BCTEUR Binance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "Time", "type": "timestamp_epoch" },
      { "selector": "4", "text": "Value", "type": "number" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api1.binance.com/api/v3/klines?symbol=BTCEUR&interval=12h",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    }
   ]
  },
  {
   "title": "Average weekly strategy profits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"StochRSICustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"StochRSICustomStrategy\" AND strategy IN($Strategies)  AND profit != -1000\n  AND symbol IN($var_symbol)\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"Lun1MarCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"Lun1MarCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"Lun5JulCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"Lun5JulCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"MACDCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"MACDCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"StableStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"StableStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"MACDInStochRSIOutCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"MACDInStochRSIOutCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"StochRSIInMACDOutCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"StochRSIInMACDOutCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"MixedStrategy1\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"MixedStrategy1\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Average daily strategy profits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"StochRSICustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"StochRSICustomStrategy\" AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"Lun1MarCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"Lun1MarCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"Lun5JulCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"Lun5JulCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"MACDCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"MACDCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"StableStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"StableStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"MACDInStochRSIOutCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"MACDInStochRSIOutCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"StochRSIInMACDOutCustomStrategy\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"StochRSIInMACDOutCustomStrategy\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    },
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"MixedStrategy1\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy = \"MixedStrategy1\" AND strategy IN($Strategies) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Average weekly profits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"Selected strategies Profit\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy IN($Strategies)  AND profit != -1000\n  AND symbol IN($var_symbol)\nGROUP BY WEEK(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Average daily profits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT DATE(updated_at) as \"time\", sum(profit) AS \"Selected strategies Profit\"\nFROM positions\nWHERE\n  $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nGROUP BY DATE(updated_at)\nORDER BY updated_at"
    }
   ]
  },
  {
   "title": "Total Profit per Symbol (Positive)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  symbol,\n  count(profit) as \"Count\",\n  avg(profit) * count(profit) AS \"Total Profit\"\nFROM positions\nWHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nGROUP BY symbol\nHAVING avg(profit) >= 0\nORDER BY avg(profit) * count(profit) DESC"
    }
   ]
  },
  {
   "title": "Total Profit per Symbol (Positive)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  symbol,\n  count(profit) as \"Count\",\n  avg(profit) * count(profit) AS \"Total Profit\"\nFROM positions\nWHERE\n   $__timeFilter(updated_at) AND strategy IN($Strategies) AND symbol IN($var_symbol) AND profit != -1000\nGROUP BY symbol\nHAVING avg(profit) < 0\nORDER BY avg(profit) * count(profit) DESC\n\n"
    }
   ]
  }
 ]
}